### PR TITLE
ENH Timed PyAv reader

### PR DESCRIPTION
**Pull request by caspervdw**
A wrapper around PyAv that interprets `duration`, `average_rate` and the timestamps per frame to give a reader with the indexed based on the timestamp of each frame. Missing frames are inserted as black frames.

Also I dropped the `PIL` dependency of the index-based PyAv reader.

### CODE REVIEW

**Comment by danielballan** [comment]
Nice idea. This looks fine to me. Thanks for cleaning up the PIL stuff.

**Comment by caspervdw** [comment]
Ok! I kept the existing reader and renamed it to `PyAvReaderIndexed`. The `PyAvVideoReader` is now an alias for the new reader.

Can be merged when Travis passes!

**Comment by caspervdw** [comment]
On some video files, the `seek` operation raises a segmentation fault, killing Python:

    Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

Do you know if there is a way to catch this? Doing the `seek` from a subprocess?

**Comment by danielballan** [comment]
I think a subprocess is the only way. This is definitely worth reporting upstream. [This recent issue](https://github.com/mikeboers/PyAV/issues/163) _might_ be related.

**Comment by caspervdw** [comment]
It indeed happens for MPEG-2 files. I'll report it upstream. For now I think this can be merged as it should be fixed upstream indeed.

**Pull request merged**
