### PR TITLE
Fix deps

### PR DESCRIPTION
**Pull request by danielballan**
This setup.py is updated to include the dependencies that we *intend* to be required. Some others are accidentally required -- this will be fixed in a separate PR.

### CODE REVIEW

**Comment by caspervdw** [comment]
@danielballan are you OK with merging the slicerator dependency now?

The 0.3 tag does not list this dependency so that every user will see an `ImportError` until he/she installs slicerator.

**Comment by danielballan** [comment]
Fair enough. I wanted to fix the long-existing problem with scipy and PIL deps too, but I'll merge this and push a v0.3.1. Tags are cheap. :- )

**Comment by danielballan** [comment]
Done! Sorry for the runaround, @caspervdw.

**Comment by danielballan** [comment]
Sigh. Caught you correct comment too late. I tagged and upload v0.3.2rc1. If it works I'll make it v0.3.2.

**Comment by caspervdw** [comment]
Sorry for my late comment and good idea to make it an rc!

Now trackpy build fails because we dropped the PIL dependency of trackpy. Seems like #186 needs to be addressed soon.

**Comment by danielballan** [comment]
Agreed.

**Pull request merged**
