### PR TITLE
modernize test suite + py311 support

### PR DESCRIPTION
**Pull request by tacaswell**
SafeConfigParser has been deprecated since Python 3.2 and will be removed in py311.

https://github.com/python/cpython/pull/28292
https://bugs.python.org/issue45173

### CODE REVIEW

**Comment by nkeim** [comment]
Thanks @tacaswell ! This looks OK to merge. Ideally we can wait until we get CI tests working again… see #393 . But if 3.11 comes out first then we should just go for it.

**Comment by tacaswell** [comment]
ok, I think I have this working, but need to do a slicerator release first.

**Comment by tacaswell** [comment]
I'm going to merge this to get GHA going.  I expect there will be some follow up PRs to fix more things...

**Comment by nkeim** [comment]
Thanks @tacaswell !!! 🎉 It's so good to have this repo back on a solid footing.

**Pull request merged**
