### PR TITLE
Update docs and tests for conda-forge

### LINKED ISSUE #242: conda-forge installation instructions
The [installation instructions](http://soft-matter.github.io/pims/v0.3.3/install.html) need to be updated to reflect the new conda-forge packaging, and to recommend Pillow for IPython display (as referenced in https://github.com/conda-forge/pims-feedstock/pull/1#issuecomment-250999894 )

### PR DESCRIPTION
**Pull request by caspervdw**
Also update docs. Closes #242 and #240.

Additonally, I've added  Py 3.5 tests + mentioned imageio and moviepy in the docs.

### CODE REVIEW

**Comment by caspervdw** [comment]
All set. I have unpinned the numpy version and added Py3.5 tests.

Do we need legacy tests? In `setup.py`, numpy is limited to 1.7. We could, for example, pin numpy to 1.7 in the first test. Some packages are not distributed below np1.10 (for the recent conda-forge additions `av` and `jpype1`), so this limits our possibilities.

**Comment by danielballan** [comment]
Hmm. At this point I would be comfortable not testing farther back than what is available on conda forge.

**Comment by caspervdw** [comment]
Ok, I did numpy==1.8 for the legacy test, for the rest it is all unpinned. Self-merging as it only touches the build and some docs.

**Comment by danielballan** [comment]
:+1:

**Pull request merged**
