### PR TITLE
Moviepy and ImageIO

### PR DESCRIPTION
**Pull request by caspervdw**
This contains some older work that I am already using for some time now:

- video readers via ImageIO and MoviePy , both packages have different implementations of an ffmpeg-based video reader via pipes
- video exporter via moviepy, similar api as the PyAv exporter
- tests for the readers

One thing, the PyAV reader seems to be tested with an expected shape that is (x, y) in stead of the conventional (y, x). @danielballan  was this intentional?

### CODE REVIEW

**Comment by danielballan** [comment]
This work probably supercedes my old work in https://github.com/soft-matter/pims/blob/master/pims/ffmpeg_reader.py

**Comment by caspervdw** [comment]
There is a thing I already discussed shortly with @danielballan on Skype. ImageIO contains a very nice  infrastructure for keeping track of all readers (`Format` classes that contain `Reader` and `Writer` classes). Each `Format` is registered in the `FormatManager` that selects the right reader for each file. `Format` exposes a `can_read` method that (optionally) includes the interpretation of the first 256 bytes of the file.

https://github.com/imageio/imageio/blob/master/imageio/core/format.py

Because this infrastructure exists already, I am considering the option of using it inside PIMS and making all of our readers ImageIO-compatible (which is not too bad because APIs are much alike).

This will include either copying over code or making imageio a required dependency.

What do you think about this?

**Comment by danielballan** [comment]
If we made imageio a required dep, what secondary required deps would that pull in?

**Comment by caspervdw** [comment]
None, the only dependency of imageio is Numpy. It downloads binaries of for instance Freeimage from their git repo when required.

**Comment by caspervdw** [comment]
Anyone :-1: on accepting ImageIO as a required dependency?

**Comment by tacaswell** [comment]
go for it.

**Comment by danielballan** [comment]
:+1:

**Comment by danielballan** [comment]
This needs a rebase, probably just in .travis.yml.

**Comment by caspervdw** [comment]
I'll close this because we chose for a different approach that makes imageio a required dep and makes use of the imageio reader selection methods.

**Pull request closed without merging**
